/**
 * A small, **license-clean** pool of example ASTM laboratory tests — the analyte codes, units, and
 * plausible value ranges `synth` draws on when populating `O` (order) and `R` (result) records. The
 * codes are **facts** (a LOINC number is a public identifier, and the local analyzer codes here are
 * invented), never a bundled terminology table (roadmap §2 "no bundled terminology; a small curated
 * license-clean pool of example codes"). Nothing clinical is asserted — a `synth` result pairs a value
 * and a code with no claim of clinical coherence (roadmap §2, the format/conformance boundary vs
 * Synthea): the pool exists only to make a *structurally* realistic result record.
 *
 * @module
 */

/** One example laboratory analyte — its codes, units, reference range, and a seeded value window. */
export interface AstmExampleTest {
  /** A local analyzer test code (invented — never a real vendor assay id). */
  readonly localCode: string;
  /** The public LOINC identifier for the analyte (a fact, not bundled terminology prose). */
  readonly loinc: string;
  /** The human-readable test name, emitted in the Universal Test ID name component. */
  readonly name: string;
  /** The units string, emitted verbatim in `R`-field 5 (never converted or guessed). */
  readonly units: string;
  /** The reference range text, emitted verbatim in `R`-field 6. */
  readonly referenceRange: string;
  /** Inclusive integer low bound of the seeded synthetic value (structural, not clinical). */
  readonly valueLow: number;
  /** Inclusive integer high bound of the seeded synthetic value. */
  readonly valueHigh: number;
  /** Number of decimal places to render the synthetic value with. */
  readonly decimals: number;
}

/**
 * The example test pool. A handful of common chemistry/hematology analytes, each with a public LOINC
 * code, invented local code, units, and a value window the seeded generator samples. Frozen — the pool
 * is shared, immutable data (roadmap §6, the immutability discipline).
 *
 * @example
 * ```ts
 * import { EXAMPLE_ASTM_TESTS } from "@cosyte/synth/astm";
 * EXAMPLE_ASTM_TESTS[0]?.name; // "Glucose"
 * ```
 */
export const EXAMPLE_ASTM_TESTS: readonly AstmExampleTest[] = Object.freeze([
  {
    localCode: "GLU",
    loinc: "2345-7",
    name: "Glucose",
    units: "mg/dL",
    referenceRange: "70-110",
    valueLow: 55,
    valueHigh: 260,
    decimals: 0,
  },
  {
    localCode: "K",
    loinc: "2823-3",
    name: "Potassium",
    units: "mmol/L",
    referenceRange: "3.5-5.1",
    valueLow: 28,
    valueHigh: 62,
    decimals: 1,
  },
  {
    localCode: "NA",
    loinc: "2951-2",
    name: "Sodium",
    units: "mmol/L",
    referenceRange: "136-145",
    valueLow: 125,
    valueHigh: 155,
    decimals: 0,
  },
  {
    localCode: "CREA",
    loinc: "2160-0",
    name: "Creatinine",
    units: "mg/dL",
    referenceRange: "0.6-1.3",
    valueLow: 4,
    valueHigh: 32,
    decimals: 1,
  },
  {
    localCode: "HGB",
    loinc: "718-7",
    name: "Hemoglobin",
    units: "g/dL",
    referenceRange: "12.0-17.5",
    valueLow: 80,
    valueHigh: 190,
    decimals: 1,
  },
  {
    localCode: "WBC",
    loinc: "6690-2",
    name: "Leukocytes",
    units: "10*3/uL",
    referenceRange: "4.5-11.0",
    valueLow: 30,
    valueHigh: 150,
    decimals: 1,
  },
  {
    localCode: "TSH",
    loinc: "3016-3",
    name: "Thyrotropin",
    units: "mIU/L",
    referenceRange: "0.40-4.50",
    valueLow: 2,
    valueHigh: 90,
    decimals: 2,
  },
  {
    localCode: "ALT",
    loinc: "1742-6",
    name: "Alanine aminotransferase",
    units: "U/L",
    referenceRange: "7-56",
    valueLow: 5,
    valueHigh: 120,
    decimals: 0,
  },
]);

/** HL7 Table 0078 abnormal-flag codes `synth` draws from (emitted verbatim; never defaulted). */
export const ASTM_ABNORMAL_FLAGS: readonly string[] = Object.freeze(["N", "L", "H", "A"]);

/** Result-status codes `synth` draws from (`F` final, `P` preliminary, `C` correction). */
export const ASTM_RESULT_STATUSES: readonly string[] = Object.freeze(["F", "P", "C"]);

/** Free-text result comments — clearly synthetic, carry no PHI. */
export const ASTM_COMMENT_TEXT: readonly string[] = Object.freeze([
  "Synthetic fixture comment - not a clinical observation.",
  "Sample generated by @cosyte/synth.",
  "Placeholder result comment for conformance testing.",
]);
