#!/usr/bin/env tsx
/**
 * scripts/determinism/verify.ts
 *
 * THE CROSS-ENGINE COMPARISON RUN. Reached by `pnpm run determinism:verify`.
 *
 * It collects one digest report per DECLARED engine and hands them to the pure decision in
 * `scripts/determinism/compare.ts`. It looks the reports up BY DECLARED ENGINE rather than by
 * listing a directory, which is the difference between a comparison that fails when an engine's
 * job stopped running and one that quietly compares whatever happens to be lying around.
 *
 * IT IS EXPECTED TO FAIL WHEN RUN LOCALLY, AND THAT IS NOT A DEFECT. A development session has one
 * Node install, so at most one of the declared reports can exist. The run then fails with the
 * missing-report diagnostic, which is the correct answer to "did every declared engine agree" when
 * one of them never spoke. CI is the first and only place the full condition exists. Everything the
 * comparison DECIDES is exercised offline in `test/determinism/cross-engine.test.ts` against
 * hand-authored fixture reports, including the mismatch case, which no local run can ever produce.
 *
 * IT TAKES NO ARGUMENTS. There is no directory flag and no engine filter: every argument to a gate
 * is a way to point it somewhere friendlier, and this one has nothing it needs to be told.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { generatedFormats } from "../oracle/formats.js";

import { compareEngines, renderComparison, type ReportSource } from "./compare.js";
import { declareCorpus } from "./corpus.js";
import { readWorkflow, reconcileDeclaredEngines, reconcileWorkflowEngines } from "./engines.js";
import { CI_WORKFLOW_PATH, readPackageFacts, readPolicy, REPORT_DIR } from "./policy.js";
import { reportFileName } from "./report.js";

/** Refuse loudly. A run that cannot do its job never reports a result from one that did not. */
function refuse(message: string): never {
  process.stderr.write(`\ndeterminism: REFUSING TO REPORT\n  ${message}\n`);
  process.exit(1);
}

async function main(): Promise<void> {
  if (process.argv.length > 2) {
    process.stderr.write(
      "determinism: this comparison takes no arguments. Every argument to a gate is a way to " +
        "point it somewhere friendlier.\n",
    );
    process.exit(2);
  }

  const policy = readPolicy();
  const facts = readPackageFacts();

  const declarationProblems = [
    ...reconcileDeclaredEngines(policy.engines, facts.engineRange),
    ...reconcileWorkflowEngines(policy.engines, readWorkflow(CI_WORKFLOW_PATH)),
  ];
  if (declarationProblems.length > 0) {
    refuse(
      "the declared supported-engine set does not reconcile, so nothing was compared:\n  - " +
        declarationProblems.join("\n  - "),
    );
  }

  const corpus = declareCorpus(policy, await generatedFormats());

  const sources = new Map<number, ReportSource>();
  for (const major of policy.engines) {
    const path = join(REPORT_DIR, reportFileName(major));
    try {
      sources.set(major, { kind: "text", label: path, text: readFileSync(path, "utf8") });
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      sources.set(major, { kind: "absent", label: path, detail: message });
    }
  }

  const result = compareEngines({
    declaredEngines: policy.engines,
    declaredPairs: corpus.graded,
    sources,
  });

  process.stdout.write(`\n${renderComparison(result)}\n`);

  if (result.status !== "pass") {
    process.stderr.write(
      "\n  Two runs in ONE process cannot disagree about the engine they run on, which is why the\n" +
        "  in-process determinism suites cannot see this break and why this comparison exists.\n\n" +
        "  IF YOU ARE RUNNING THIS LOCALLY, a missing-report failure is the expected answer: one\n" +
        "  development session has one Node install, and the full multi-engine condition exists\n" +
        "  only in continuous integration.\n\n" +
        "  IF THIS IS CI AND TWO ENGINES DISAGREED: fix the harness if the digest is not a pure\n" +
        "  function of the generated bytes (an unstable iteration order, a clock or a path leaking\n" +
        "  into a digest). If the divergence is genuinely in generated output, that is a real\n" +
        "  cross-engine break in the seed-to-bytes mapping and it is a finding, not a thing to\n" +
        "  make green. Narrowing the DECLARED corpus is allowed only by naming the excluded\n" +
        "  (format, seed) pair and its reason in scripts/determinism/determinism-policy.json,\n" +
        "  which is checked and is not a tolerance. There is no severity downgrade, no\n" +
        "  warning-only mode and no suppression list in this gate, deliberately.\n",
    );
    process.exit(1);
  }
}

await main();
