/**
 * scripts/oracle/corpus.ts
 *
 * THE DECLARED SEED CORPUS: WHAT THE ORACLE ASKS ABOUT.
 *
 * The corpus is DECLARED, in a committed file, as a list of (generator kind, seed) pairs. Two
 * properties follow from that and both are load-bearing:
 *
 *   * IT IS REPRODUCIBLE BY SEED RATHER THAN BY RERUN. Every artifact the validator sees is
 *     regenerated byte-identically from the seed written next to it, on any machine, so a finding
 *     names something a reader can put back in front of the validator without access to the job.
 *   * IT IS NARROWABLE ONLY IN THE OPEN. Taking an artifact out of the graded set means writing an
 *     `excluded` reason beside it, which the coverage declaration then publishes and the gate
 *     refuses to count toward the pass. There is no other way to make the corpus smaller, and there
 *     is no way at all to make a finding smaller.
 *
 * THE PROFILE IS NOT DECLARED, IT IS READ OFF THE ARTIFACT. Every generated US Core resource stamps
 * its own `meta.profile`, so the profile the validator is pointed at is the one the artifact itself
 * claims. Writing the profile down beside the seed would let the two drift, and a run that graded a
 * resource against a profile it does not claim would be measuring the wrong thing while looking
 * right. An artifact that claims no profile is refused rather than graded against a default.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";

import { fhirCorpus, type FhirResourceKind } from "../../src/fhir/index.js";

import { REPO_ROOT } from "./formats.js";
import type { DeclaredArtifact, ExcludedArtifact } from "./gate.js";

/** Where the committed corpus declaration lives (it shares a file with the coverage policy). */
export const CORPUS_DECLARATION_PATH = join(REPO_ROOT, "scripts", "oracle", "coverage-policy.json");

/** One declared corpus member. */
export interface CorpusDeclarationEntry {
  /** The generator kind, as `fhirCorpus`'s mix spells it. */
  readonly kind: string;
  /** The seed it is generated from. */
  readonly seed: number;
  /** When present, why this artifact is NOT graded. Never a statement about a finding. */
  readonly excluded?: string;
}

/** An artifact that will be graded, with the bytes to hand to the validator. */
export interface CorpusArtifact {
  /** Its identity, carrying the format and the reproducing seed. */
  readonly artifact: DeclaredArtifact;
  /** The serialized wire text the generator produced. */
  readonly content: string;
}

/** The generated corpus: what is graded, and what is declared and deliberately not. */
export interface GeneratedCorpus {
  /** Artifacts to submit to the validator. */
  readonly graded: readonly CorpusArtifact[];
  /** Artifacts declared and taken out, each with its reason. */
  readonly excluded: readonly ExcludedArtifact[];
}

/** True for a plain JSON object. */
const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * Read the committed corpus declaration.
 *
 * @param path - The declaration file. Defaults to the committed one.
 * @returns The declared entries, in file order.
 * @throws Error when the declaration is missing, empty or malformed. An empty corpus is refused
 *   here as well as at the gate: a run has to know it was asked to grade something.
 * @example
 * ```ts
 * const entries = readCorpusDeclaration();
 * entries.length > 0; // true
 * ```
 */
export function readCorpusDeclaration(
  path: string = CORPUS_DECLARATION_PATH,
): readonly CorpusDeclarationEntry[] {
  const parsed: unknown = JSON.parse(readFileSync(path, "utf8"));
  if (!isRecord(parsed) || !Array.isArray(parsed["corpus"])) {
    throw new Error(`${path} has no \`corpus\` array, so the oracle has nothing declared to grade`);
  }
  const entries: CorpusDeclarationEntry[] = [];
  for (const [index, raw] of parsed["corpus"].entries()) {
    if (!isRecord(raw)) throw new Error(`${path}: corpus[${String(index)}] is not an object`);
    const kind = raw["kind"];
    const seed = raw["seed"];
    if (typeof kind !== "string" || kind.length === 0) {
      throw new Error(`${path}: corpus[${String(index)}] has no generator kind`);
    }
    if (typeof seed !== "number" || !Number.isInteger(seed) || seed < 0) {
      throw new Error(
        `${path}: corpus[${String(index)}] ("${kind}") has no whole-number seed, so the artifact ` +
          "it names could not be regenerated from this declaration.",
      );
    }
    const excluded = raw["excluded"];
    if (excluded !== undefined && (typeof excluded !== "string" || excluded.trim().length === 0)) {
      throw new Error(
        `${path}: corpus[${String(index)}] ("${kind}") is excluded with no reason. An exclusion ` +
          "is named and reasoned in the open or it is not made.",
      );
    }
    entries.push(
      excluded === undefined ? { kind, seed } : { kind, seed, excluded: excluded.trim() },
    );
  }
  if (entries.length === 0) {
    throw new Error(
      `${path}: the declared corpus is empty. A gate with nothing to grade is refused here rather ` +
        "than allowed to report a pass over nothing.",
    );
  }
  return entries;
}

/** The `meta.profile` a generated resource claims, or `undefined`. */
function claimedProfile(content: string): string | undefined {
  const parsed: unknown = JSON.parse(content);
  if (!isRecord(parsed)) return undefined;
  const meta = parsed["meta"];
  if (!isRecord(meta)) return undefined;
  const profiles = meta["profile"];
  if (!Array.isArray(profiles)) return undefined;
  const first = profiles.find((p): p is string => typeof p === "string" && p.length > 0);
  return first;
}

/** A stable, readable artifact id: format, kind, and the seed that reproduces it. */
export const artifactId = (format: string, kind: string, seed: number): string =>
  `${format}/${kind}/seed-${String(seed)}`;

/** What a corpus factory has to hand back for this file to use it. */
export interface GeneratorResult {
  /** The generated artifacts, each carrying the format label the library gives it. */
  readonly artifacts: readonly {
    readonly format: string;
    readonly kind: string;
    readonly content: string;
  }[];
}

/** A corpus factory, injectable so the refusal paths can be driven without a real generator. */
export type CorpusGenerator = (options: {
  readonly seed: number;
  readonly count: number;
  readonly mix: readonly string[];
}) => GeneratorResult;

/**
 * The real generator: this package's FHIR corpus factory, behind a signature that takes the kind as
 * a plain string.
 *
 * THE CAST IS JUSTIFIED BY A RUNTIME CHECK, NOT BY CONFIDENCE. `fhirCorpus` resolves every mix entry
 * against its own closed set through `resolveMix` before generating anything, and an unrecognised
 * kind is a fatal `SYNTH_UNSUPPORTED_KIND`. So a kind the declaration invented fails loudly at the
 * library's own chokepoint rather than generating something else and mislabelling it, which is the
 * failure that chokepoint exists to prevent. The alternative, teaching this file the closed set, would
 * duplicate it and let the copy drift.
 */
export const fhirCorpusGenerator: CorpusGenerator = (options) =>
  fhirCorpus({
    seed: options.seed,
    count: options.count,
    mix: options.mix as readonly FhirResourceKind[],
  });

/**
 * Generate the declared corpus.
 *
 * @param entries - The declared entries.
 * @param generate - The corpus factory, injected so a test can drive this without the FHIR peer.
 * @returns The graded artifacts with their bytes, and the declared exclusions.
 * @throws Error when a declared kind generates nothing, or a generated resource claims no profile.
 * @example
 * ```ts
 * const corpus = generateDeclaredCorpus(readCorpusDeclaration(), fhirCorpus);
 * corpus.graded.length > 0; // true
 * ```
 */
export function generateDeclaredCorpus(
  entries: readonly CorpusDeclarationEntry[],
  generate: CorpusGenerator,
): GeneratedCorpus {
  const graded: CorpusArtifact[] = [];
  const excluded: ExcludedArtifact[] = [];

  for (const entry of entries) {
    const corpus = generate({ seed: entry.seed, count: 1, mix: [entry.kind] });
    const generated = corpus.artifacts[0];
    if (generated === undefined) {
      throw new Error(
        `the declared corpus names "${entry.kind}" at seed ${String(entry.seed)} and the ` +
          "generator produced nothing for it. A declaration that names an artifact the library " +
          "does not generate is refused rather than quietly dropped.",
      );
    }

    const id = artifactId(generated.format, entry.kind, entry.seed);

    if (entry.excluded !== undefined) {
      excluded.push({
        artifact: {
          id,
          format: generated.format,
          kind: entry.kind,
          seed: entry.seed,
          profile: claimedProfile(generated.content) ?? "",
        },
        reason: entry.excluded,
      });
      continue;
    }

    const profile = claimedProfile(generated.content);
    if (profile === undefined) {
      throw new Error(
        `${id} claims no meta.profile, so there is no profile to grade it against. Refusing ` +
          "rather than falling back to a default: grading a resource against a profile it does " +
          "not claim measures the wrong thing while looking right.",
      );
    }

    graded.push({
      artifact: { id, format: generated.format, kind: entry.kind, seed: entry.seed, profile },
      content: generated.content,
    });
  }

  return { graded, excluded };
}
